{{- if and (not .Values.database.existingSecret) .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-api.fullname" . }}-db
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
  username: {{ .Values.database.user | b64enc | quote }}
{{- end }}
---
{{- if not .Values.keycloak.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-api.fullname" . }}-keycloak
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  client-secret: {{ .Values.keycloak.clientSecret | b64enc | quote }}
{{- end }}
