apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-api.fullname" . }}
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "user-api.selectorLabels" . | nindent 4 }}
---
{{- if .Values.healthService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-api.fullname" . }}-health
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: health
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.healthService.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "user-api.selectorLabels" . | nindent 4 }}
{{- end }}
